openshift-psap/matrix-benchmarking

matrix_benchmarking/download.py, matrix_benchmarking/plotting/prom/__init__.py, matrix_benchmarking/plotting/prom/cpu_memory.py, matrix_benchmarking/plotting/ui/__init__.py
* `matrix_benchmarking/plotting/prom/cpu_memory.py: do not crash if results has no thresholds`
---
* `matrix_benchmarking/plotting/prom/__init__.py: do not crash if results has no thresholds`
---
* `matrix_benchmarking/plotting/prom/__init__.py: check threshold criteria`
---
* `matrix_benchmarking/plotting/prom/cpu_memory.py: check threshold criteria`
---
=> Thresholds

matrix_benchmarking/cli_args.py, matrix_benchmarking/common.py, matrix_benchmarking/download_lts.py, matrix_benchmarking/main.py, matrix_benchmarking/parse.py, matrix_benchmarking/store/simple.py, matrix_benchmarking/upload_lts.py, requirements.txt
This PR allows for runs to be uploaded to Horreum.
This adds 2 new commands
- `upload_lts` to upload runs to Horreum
- `download_lts` to download runs from Horreum
This is blocked by [ci-artificats #642](https://github.com/openshift-psap/ci-artifacts/pull/642)
=> Horreum Uploading/Downloading/Parsing

matrix_benchmarking/plotting/ui/__init__.py
=> matrix_benchmarking/plotting/ui/__init__.py: do not catch bdb.BdbQuit exceptions

matrix_benchmarking/parse.py
Added pretty option to parse for output_lts for pretty print, default is True.
When true, adds 4 spaces for each indent level.
When false, a minified JSON string is outputted.
=> Horreum Parsing JSON Pretty Print

matrix_benchmarking/common.py, matrix_benchmarking/download_lts.py, matrix_benchmarking/plotting/prom/__init__.py, matrix_benchmarking/plotting/prom/cpu_memory.py
This PR expands out a MatrixEntry to support LTS payloads.
General structure expected:
```json5
{
data: {
metrics: { 
...
},
thresholds: {
...
},
...
},
metadata: {
...
}
}
```
=>  LTS MatrixEntry support

matrix_benchmarking/models.py
Causes https://github.com/pydantic/pydantic/issues/545 exception
=> matrix_benchmarking/models.py: disable payload_schema

matrix_benchmarking/models.py
This PR introduces some improvements to the base models, and adds a function for schema validation
=> LTS Improvements

matrix_benchmarking/cli_args.py, matrix_benchmarking/store/simple.py
`settings` files are now deprecated.
=> matrix_benchmarking/store/simple.py: update to use settings.yaml as default

matrix_benchmarking/benchmark.py, matrix_benchmarking/download.py, matrix_benchmarking/export_lts_schema.py, matrix_benchmarking/parse.py, matrix_benchmarking/plotting/ui/__init__.py, matrix_benchmarking/store/__init__.py, matrix_benchmarking/upload_lts.py, matrix_benchmarking/visualize.py
The workload package can now be passed directly with the `--workload` parameter
=> Update the workload location

matrix_benchmarking/cli_args.py, matrix_benchmarking/download_lts.py
@kpouget Builds on top of #117.
=> Add filter support to LTS download from OpenSearch

matrix_benchmarking/parse.py, matrix_benchmarking/upload_lts.py, workloads
This reverts commit 38cb2cd36f38811bf0770ddb5f27b5215ec14e4d.
=> Revert "matrix_benchmarking/upload_lts.py: disable LTS upload"

matrix_benchmarking/plotting/prom/__init__.py
=> matrix_benchmarking/plotting/prom/__init__.py: filter the tests_timestamp settings with the variable list

matrix_benchmarking/analyze/report.py
=> matrix_benchmarking: analyze: report: make the version sorting more reliable

matrix_benchmarking/analyze/report.py
=> matrix_benchmarking: analyze: report: improve the sorting of the historical entries

matrix_benchmarking/store/prom_db.py
=> matrix_benchmarking: store: prom_db: make sure the deduplicated TS don't overlap

matrix_benchmarking/analyze/report.py, matrix_benchmarking/analyze_lts.py
=> matrix_benchmarking: analyze_lts: generate a YAML summary for the regression analyze

matrix_benchmarking/plotting/ui/report.py
=> matrix_benchmarking: plotting: ui/report: log the stack trace along with the exception

matrix_benchmarking/analyze/report.py
=> matrix_benchmarking: analyze: report: cast to str before calling `.replace`

requirements.txt
=> requirements.txt: use a fork of Hunter to pin numpy package

matrix_benchmarking/analyze/report.py
=> matrix_benchmarking: analyze: report: improve to ease the KPI table report generation

requirements.txt
This reverts commit 78e0f712824b652d20b8f29e81e37fadf1ffc94f.
=> Revert "Pinned boto3==1.35.59 to a specific version, as it is required by awscli-1.36.0 in project/topsail"

matrix_benchmarking/downloading/scrape/ocp_ci.py
=> matrix_benchmarking: downloading: scrape/ocp_ci: update to exclude simple links after artifact template update
